config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  scope '/:locale' do
    root to: 'home#index'

    get 'home/index'

    get 'styles/atoms'

    get 'styles/molecules'

    get 'styles/organisms'

    resources :sessions, only: [:new, :create, :destroy]

    resources :users, only: [:new, :create, :edit, :update] do
      resources :goals
    end

    resources :ideas do
      resources :comments
      resources :photos
    end

    get 'account', to: 'account#edit'
    patch 'account', to: 'account#update'
    get 'account/ideas'
    get 'account/goals'

    get 'login', to: 'sessions#new'

    get 'signup', to: 'users#new'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :idea
  belongs_to :user
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 75 }

  belongs_to :user

  has_many :comments

  has_and_belongs_to_many :users

  scope :most_recent,          -> { order(created_at: :desc).limit(3) }
  scope :title_contains,       ->(term) { where('title LIKE ?', "%#{term}%") }
  scope :description_contains, ->(term) { where('description LIKE ?', "%#{term}%") }
  scope :search, ->(search_term) { title_contains(search_term).or(description_contains(search_term)) }

  paginates_per 9
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :ideas

  has_and_belongs_to_many :goals, class_name: 'Idea'

  has_secure_password

  validates :email, uniqueness: true
  validates :role, inclusion: { in: %w(registered admin) }

  after_initialize :default_role!
  before_validation :downcase_email

  mount_uploader :avatar, AvatarUploader

  private

  def downcase_email
    self.email = email.downcase if email #prevent from users with email:Nil in database
  end

  def default_role!
    self.role ||= 'registered'
  end
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  before_action :ensure_authenticated

  def edit
  end

  def update
    current_user.update(user_params)
    redirect_to account_path
  end

  def ideas
    user = User.find(session[:user_id])
    @ideas = user.ideas
  end

  def goals
    @goals = current_user.goals
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :avatar)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :ensure_authenticated

  def create
    @idea = Idea.find(params[:idea_id])

    current_user.goals << @idea

    respond_to do |format|
      format.html { redirect_to idea_path(@idea) }
      format.js
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ideas = Idea.most_recent
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  include RolesHelper

  before_action :ensure_authenticated,   only: [:new, :create, :edit, :update] #this will stop any resources being loaded unnecessarily for anonymous users
  before_action :load_idea,              only: [:edit, :update, :destroy] #this will load Idea record before executing `ensure_owner` filter
  before_action :authorize_to_edit_idea, only: [:edit, :update, :destroy] #this make use of the Idea instance

  def index
    @search_term = params[:q]
    logger.info("Search completed using #{@search_term}.")
    @ideas = Idea.search(@search_term).page(params[:page])
  end

  def show
    @idea = Idea.find(params[:id])
    @comment = Comment.new
    @display_add_comment = session[:user_id].present?

    if(logged_in?) #check whether users are logged in or not
      @disable_add_goal = current_user.goals.exists?(@idea.id)
    end
  end

  def new
    @idea = Idea.new
  end

  def create
    user = User.find(session[:user_id])
    @idea = Idea.new(idea_resource_params)
    @idea.user = user
    if @idea.save
      redirect_to(ideas_path)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @idea.update(idea_resource_params)
      redirect_to(account_ideas_path)
    else
      render 'edit'
    end
  end

  def destroy
    @idea.destroy!
  end

  private

  def idea_resource_params
    params.require(:idea).permit(:title, :description, :photo_url, :done_count, :name_of_user)
  end

  def load_idea
    @idea = Idea.find(params[:id])
  end

  def authorize_to_edit_idea
    redirect_to(account_path) unless(can_edit?(@idea))
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  include RolesHelper

  before_action :ensure_authenticated
  before_action :load_idea
  before_action :authorize

  def index
    @query = params[:query]
    @query = @idea.title if @query.blank?

    @photos = Unsplash::Photo.random(query: @query, count: 3) # this returns an array of photos
  end

  def create
    @idea.update_attributes photo_url: params[:photo_url]

    redirect_to edit_idea_path(@idea)
  end

  private

  def load_idea
    @idea = Idea.find(params[:idea_id])
  end

  def authorize
    redirect_to account_path unless can_edit?(@idea)
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  def atoms
  end

  def molecules
  end

  def organisms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_admin, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if(@user.save)
      session[:user_id] = @user.id
      redirect_to ideas_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if(@user.update(edit_user_params))
      redirect_to account_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def edit_user_params
    params.require(:user).permit(:email, :name, :role)
  end

  def ensure_admin
     if(current_user.role == 'admin')
       return
     end

    redirect_to account_path
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
  # def has_goal?(goal)
  #   return false unless logged_in?
  # else
  #   return true
  # end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
  def can_edit?(goal)
    case(current_user.role)
    when 'admin' then true
    when 'registered' then current_user == goal.user
    else false
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/create.js.erb
var svgUse = document.createElementNS("http://www.w3.org/2000/svg", 'use');
svgUse.setAttribute('href', '<%= image_path("icons/icons-defs.svg") %>#delete');

var svgHeart = document.createElementNS("http://www.w3.org/2000/svg", "svg");
svgHeart.setAttribute('class', 'icon-delete');
svgHeart.setAttribute('role', 'presentation');
svgHeart.appendChild(svgUse);

var buttonText = document.createTextNode('Remove Goal');

var removeGoalLink = document.createElement('a');
removeGoalLink.className = 'card__btn delta';
removeGoalLink.appendChild(svgHeart);
removeGoalLink.appendChild(buttonText);

var addGoalLink = document.getElementById('goal-<%= @idea.id %>');
addGoalLink.parentNode.replaceChild(removeGoalLink, addGoalLink);

app/views/home/index.html.erb
<main>
  <div class="masthead">
    <div class="content-wrapper">
      <h1>Get inspired. Create your bucket list. Share.</h1>
      <%= render(partial: 'search_form') %>
    </div>
  </div>
  <div class="content-wrapper ">
    <h2>Some ideas</h2>
    <ul class="bare-list float-grid css-grid ">
      <% @ideas.each do |idea| %>
        <li>
          <%= render(partial: 'idea_card',
                    locals: { card_title: idea.title,
                              done_count: idea.done_count,
                              photo_url: idea.photo_url,
                              idea: idea }) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="see-more ">
    <%= button_tag(class: "btn", type: "button") do %>
      <%= link_to "See more", ideas_path %>
    <% end %>
  </div>
</main>

app/views/photos/index.html.erb
<main>
  <div class="content-wrapper">
    <nav>
      <ul class="sub-navigation">
        <li><%= link_to('Idea', edit_idea_path(@idea)) %></li>
        <li><a href="#nolink" class="current">Photos</a></li>
      </ul>
    </nav>
    <h1>Suggested</h1>
    <div class="content-wrapper">
      <%= form_tag(idea_photos_path(@idea), method: :get, class: 'form--inpage') do %>
        <div class="input-inline">
          <label class="input-group__label" for="query">Change search term</label>
          <div class="input-row">
            <%= text_field_tag(:query, @query, class: 'input-row__field') %>
            <input name="query" id="query" value="" class="input-row__field" type="text">
            <button class="btn btn--primary btn--inline" type="submit">Go</button>
          </div>
        </div>
      <% end %>

      <ul class="bare-list float-grid css-grid">
        <% @photos.each do |photo| %>
          <li>
            <div class="card">
              <div class="card__thumb">
                <%= image_tag(photo.urls.regular) %>
              </div>
            </div>
            <%= form_tag(idea_photos_path(@idea)) do %>
              <div class="prompt">
                <%= hidden_field_tag(:photo_url, photo.urls.regular) %>
                <%= submit_tag('Use this photo', class: 'btn btn--primary prompt__confirm') %>
              </div>
            <% end %>
            <p>Photo taken by <%= photo.user.name %>, available at <%= link_to('unsplash.com', photo.links.html) %></p>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</main>

app/views/styles/_button.html.erb
<button class="btn" type="button"><%= label %></button>

app/views/styles/_link_button.html.erb
<a class="btn" href="#nolink"><%= label %></a>

app/views/styles/_logo.html.erb
<div class="logo">
  <a href="/">
    <span>
      <i>My</i>
      Bucket List</span></a>
</div>

app/views/styles/_negative_button.html.erb
<button class="btn btn--warning" type="button"><%= label %></button>

app/views/styles/_negative_logo.html.erb
<div class="sg-dark-bg">
  <div class="logo logo--inverted footer__logo">
    <a href="/">
      <span>
        <i>My</i>
        Bucket List</span></a>
  </div>
</div>

app/views/styles/_primary_button.html.erb
<button class="btn btn--primary" type="button"><%= label %></button>

app/views/styles/_prompt.html.erb
<div class="prompt">
  <a class="prompt__cancel" href="#cancel">Cancel</a>
  <button class="btn btn--primary prompt__confirm" type="submit"><%= prompt_label %></button>
</div>

app/views/styles/_search_control.html.erb
<div class="input-inline">
  <label class="input-group__label" for="global-search-input">Looking for inspiration?</label>
  <div class="input-row">
    <input id="global-search-input" class="input-row__field" type="text" name="global-search" placeholder="e.g. Swimming with dolphins">
    <button class="btn btn--inline" type="submit">Search</button>
  </div>
</div>

app/views/styles/_sub_nav_item.html.erb
<% if(current == true) %>
  <li><%= link_to(title, uri, class: 'current') %></li>
<% else %>
  <li><%= link_to(title, uri) %></li>
<% end %>

app/views/styles/atoms.html.erb
<main class="content-wrapper">
  <div>
    <h1>Style Guide</h1>
    <p>
      Our Style Guide is based upon the principles of Atomic design, a methodology composed of five distinct stages working together to create interface design systems in a more deliberate and hierarchical manner.
    </p>
    <nav>
      <ul class="sub-navigation">
        <%= render(partial: 'sub_nav_item', locals: { title: 'Atoms', uri: styles_atoms_path, current: true }) %>
        <%= render(partial: 'sub_nav_item', locals: { title: 'Molecules', uri: styles_molecules_path, current: false }) %>
        <%= render(partial: 'sub_nav_item', locals: { title: 'Organisms', uri: styles_organisms_path, current: false }) %>
        <li>
          <a href="#templates.html">Templates</a>
        </li>
        <li>
          <a href="#pages">Pages</a>
        </li>
      </ul>
    </nav>
    <h2>Atoms</h2>
    <p>
      Atoms are the basic building blocks of matter. Applied to web interfaces, atoms are our HTML tags, such as a form label, an input or a button.
    </p>
    <p>
      Atoms can also include more abstract elements like color palettes, fonts and even more invisible aspects of an interface like animations.
    </p>
    <p>
      Like atoms in nature they’re fairly abstract and often not terribly useful on their own. However, they’re good as a reference in the context of a pattern library as you can see all your global styles laid out at a glance.
    </p>
    <nav>
      <ol class="ordered-navigation">
        <li>
          <a href="#palette">Palette</a>
        </li>
        <li>
          <a href="#typography">Typography</a>
        </li>
        <li>
          <a href="#buttons">Buttons</a>
        </li>
        <li>
          <a href="#forms">Form Elements</a>
        </li>
        <li>
          <a href="#icons">Icons</a>
        </li>
      </ol>
    </nav>
  </div>
  <section class="sg-section" id="palette">
    <h3 class="beta">01. Palette</h3>
    <ul class="sg-palette">
      <li>
        <div data-bgcolor="blue"></div>
        <p>#2c9cf2</p>
      </li>
      <li>
        <div data-bgcolor="black"></div>
        <p>#192127</p>
      </li>
      <li>
        <div data-bgcolor="darkest"></div>
        <p>#72797e</p>
      </li>
      <li>
        <div data-bgcolor="dark"></div>
        <p>#afbac4</p>
      </li>
      <li>
        <div data-bgcolor="gray"></div>
        <p>#bbc1c6</p>
      </li>
      <li>
        <div data-bgcolor="light"></div>
        <p>#e3e5e9</p>
      </li>
      <li>
        <div data-bgcolor="lightest"></div>
        <p>#f7f9fc</p>
      </li>
      <li>
        <div data-bgcolor="red"></div>
        <p>#e25d43</p>
      </li>
    </ul>
  </section>
  <section class="sg-section" id="typography">
    <h3 class="beta">02. Typography</h3>
    <div class="sg-inlineblock">
      <h4>Glyph</h4>
      <p class="giga">Aa</p>
    </div>
    <div class="sg-inlineblock sg-weights">
      <h4>Weights</h4>
      <ul class="bare-list">
        <li>Regular</li>
        <li>
          <em>Regular Italic</em>
        </li>
        <li>
          <strong>Bold</strong>
        </li>
        <li>
          <strong>
            <em>Bold Italic</em>
          </strong>
        </li>
      </ul>
    </div>
    <table class="table--lines sg-typotable">
      <thead>
        <tr>
          <th>Style</th>
          <th>Desktop</th>
          <th>Tablet</th>
          <th>Mobile</th>
          <th>Line-height</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="alpha">H1 / .alpha</td>
          <td>48px</td>
          <td>40px</td>
          <td>36px</td>
          <td>1.2</td>
        </tr>
        <tr>
          <td class="beta">H2 / .beta</td>
          <td>36px</td>
          <td>32px</td>
          <td>28px</td>
          <td>1.2</td>
        </tr>
        <tr>
          <td class="gamma">H3 / .gamma</td>
          <td>28px</td>
          <td>28px</td>
          <td>24px</td>
          <td>1.2</td>
        </tr>
        <tr>
          <td class="delta">H4 / .delta</td>
          <td>13px</td>
          <td>13px</td>
          <td>13px</td>
          <td>1.5</td>
        </tr>
        <tr>
          <td class="epsilon">H5 / .epsilon</td>
          <td>14px</td>
          <td>14px</td>
          <td>14px</td>
          <td>1.4</td>
        </tr>
        <tr>
          <td class="zeta">H6 / .zeta</td>
          <td>12px</td>
          <td>12px</td>
          <td>12px</td>
          <td>1.4</td>
        </tr>
        <tr>
          <td class="sg-header-button">Action/Button</td>
          <td>13px</td>
          <td>13px</td>
          <td>13px</td>
          <td>1</td>
        </tr>
        <tr>
          <td>Paragraph text</td>
          <td>15px</td>
          <td>15px</td>
          <td>15px</td>
          <td>1.6</td>
        </tr>
      </tbody>
    </table>
  </section>
  <section class="sg-section" id="buttons">
    <h3 class="beta">03. Buttons</h3>
    <h4>Default button</h4>
    <div>
      <%= render(partial: 'button', locals: { label: 'Button' }) %>
      <%= render(partial: 'link_button', locals: { label: 'Link Button' }) %>
    </div>
    <h4>Primary button</h4>
    <div>
      <%= render(partial: 'primary_button', locals: { label: 'Primary button'}) %>
    </div>
    <h4>Negative button</h4>
    <div>
      <%= render(partial: 'negative_button', locals: { label: 'Warning button'}) %>
    </div>
  </section>
  <section class="sg-section" id="forms">
    <h3 class="beta">04. Form Elements</h3>
    <div>
      <h4 class="gamma">Input field</h4>
      <div class="input-group input-group--horizontal">
        <label class="input-group__label" for="sg-input">Input label</label>
        <input id="sg-input" class="input-group__field" type="text" name="sg-input" placeholder="Placeholder text">
      </div>
    </div>
    <div>
      <h4 class="gamma">Text area</h4>
      <div class="input-group input-group--horizontal">
        <label class="input-group__label" for="sg-textarea">Text area label</label>
        <textarea id="sg-textarea" class="input-group__field"></textarea>
      </div>
    </div>
    <div>
      <h4 class="gamma">Validation message on 1 column form</h4>
      <div class="alert">
        Please fill out a valid email address.
        <p>Please enter name.</p>
        <ul>
          <li>Phone number missing.</li>
          <li>Postcode missing.</li>
        </ul>
      </div>
    </div>
    <div>
      <h4 class="gamma">Validation message on 2 column form</h4>
      <div class="alert alert--wide">
        Please fill out a valid email address.
        <p>Please enter name.</p>
        <ul>
          <li>Phone number missing.</li>
          <li>Postcode missing.</li>
        </ul>
      </div>
    </div>
  </section>
  <section class="sg-section" id="icons">
    <h3 class="beta">05. Icons</h3>
    <div>
      <ul>
        <li>
          <svg class="icon-heart" role="presentation">
            <use xlink:href="<%= asset_url("icons/icons-defs.svg" + "#heart") %>"></use>
            <%# <use xlink:href="images/icons-defs.svg#heart"></use> %>
          </svg>
        </li>
        <li>
          <svg class="icon-heart icon-heart--liked" role="presentation">
            <use xlink:href="<%= asset_url("icons/icons-defs.svg" + "#heart") %>"></use>
            <%# <use xlink:href="images/icons-defs.svg#heart"></use> %>
          </svg>
        </li>
        <li>
          <svg class="icon-pluss" role="presentation">
            <use xlink:href="<%= asset_url("icons/icons-defs.svg" + "#pluss") %>"></use>
            <%# <use xlink:href="images/icons-defs.svg#pluss"></use> %>
          </svg>
        </li>
        <li>
          <svg class="icon-edit" role="presentation">
            <use xlink:href="<%= asset_url("icons/icons-defs.svg" + "#edit") %>"></use>
            <%# <use xlink:href="images/icons-defs.svg#edit"></use> %>
          </svg>
        </li>
        <li>
          <svg class="icon-delete" role="presentation">
            <use xlink:href="<%= asset_url("icons/icons-defs.svg" + "#delete") %>"></use>
          </svg>
        </li>
        <li>
          <svg class="icon-edit" role="presentation">
            <use xlink:href="<%= asset_url("icons/icons-defs.svg" + "#edit") %>"></use>
            <%# <use xlink:href="images/icons-defs.svg#edit"></use> %>
          </svg>
        </li>
      </ul>
    </div>
  </section>
</main>

app/views/styles/molecules.html.erb
<body>
  <main class="content-wrapper">
    <div>
      <h1>Style Guide</h1>
      <p>
        Our Style Guide is based upon the principles of Atomic design, a methodology composed of five distinct stages working together to create interface design systems in a more deliberate and hierarchical manner.
      </p>
      <nav>
        <ul class="sub-navigation">
          <%= render(partial: 'sub_nav_item', locals: { title: 'Atoms', uri: styles_atoms_path, current: false }) %>
          <%= render(partial: 'sub_nav_item', locals: { title: 'Molecules', uri: styles_molecules_path, current: true }) %>
          <%= render(partial: 'sub_nav_item', locals: { title: 'Organisms', uri: styles_organisms_path, current: false }) %>
          <li>
            <a href="#templates.html">Templates</a>
          </li>
          <li>
            <a href="#pages">Pages</a>
          </li>
        </ul>
      </nav>
      <h1>Molecules</h1>
      <p>
        Things start getting more interesting and tangible when we start combining atoms together. Molecules are groups of atoms bonded together and are the smallest fundamental units of a compound. These molecules take on their own properties and serve as
        the backbone of our design systems.
      </p>
      <p>
        For example, a form label, input or button isn't too useful by itself, but combine them together as a form and now they can actually do something.
      </p>
      <p>
        Building up to molecules from atoms encourages a “do one thing and do it well” mentality. While molecules can be complex, as a rule of thumb they are relatively simple combinations of atoms built for reuse.
      </p>
      <nav>
        <ol class="ordered-navigation">
          <li>
            <a href="#card">Card</a>
          </li>
          <li>
            <a href="#logo">Logo</a>
          </li>
          <li>
            <a href="#search">Search</a>
          </li>
          <li>
            <a href="#navigation">Navigation</a>
          </li>
          <li>
            <a href="#cancel-confirm">Cancel / Confirm prompt</a>
          </li>
          <li>
            <a href="#like">Like / Liked button</a>
          </li>
        </ol>
      </nav>
    </div>
    <section class="sg-section" id="card">
      <h2>01. Card</h2>
      <%= render(partial: 'idea_card', locals: { card_title: 'See the Northern lights', done_count: 25, photo_url: 'http://fpoimg.com/255x170', idea: 1 }) %>
    </section>
    <section class="sg-section" id="logo">
      <h2>02. Logo</h2>
      <h3>Default logo</h3>
      <%= render(partial: 'logo') %>
      <h3>Negative logo</h3>
      <p>Used on dark background, like in the site footer.</p>
      <%= render(partial: 'negative_logo') %>
    </section>
    <section class="sg-section" id="search">
      <h2>03. Search</h2>
      <%= render(partial: 'search_control') %>
    </section>
    <section class="sg-section" id="navigation">
      <h2>04. Navigation</h2>
      <h3>Primary navigation</h3>
      <nav class="site-header__nav">
        <ul class="main-navigation">
          <li>
            <a href="#nolink">Inspiration</a>
          </li>
          <li>
            <a href="#nolink">Sign Up</a>
          </li>
          <li>
            <a href="#nolink">Log In</a>
          </li>
        </ul>
      </nav>
      <h3>Secondary navigation</h3>
      <nav>
        <ul class="sub-navigation">
          <li>
            <%= link_to('Atoms', '/styles/atoms') %>
          </li>
          <li>
            <a href="molecules.html" class="current">Molecules</a>
          </li>
          <li>
            <%= link_to('Organisms', '/styles/organisms') %>
          </li>
          <li>
            <a href="#templates">Templates</a>
          </li>
          <li>
            <a href="#pages">Pages</a>
          </li>
        </ul>
      </nav>
      <h3>Footer navigation</h3>
      <div class="sg-dark-bg">
        <nav class="footer__navigation">
          <ul>
            <li>
              <a href="#nolink">About</a>
            </li>
            <li>
              <a href="#nolink">Style Guide</a>
            </li>
            <li>
              <a href="#nolink">Terms of Use</a>
            </li>
          </ul>
        </nav>
      </div>
      <h3>Pagination</h3>
      <div>
        <ul class="pagination">
          <li>
            <a href="#nolink">First</a>
          </li>
          <li>
            <a href="#nolink">Previous</a>
          </li>
          <li>...</li>
          <li>
            <a href="#nolink">5</a>
          </li>
          <li>
            <a href="#nolink" class="current">6</a>
          </li>
          <li>
            <a href="#nolink">7</a>
          </li>
          <li>...</li>
          <li>
            <a href="#nolink">Next</a>
          </li>
          <li>
            <a href="#nolink">Last</a>
          </li>
        </ul>
      </div>
      <h3>Filters</h3>
      <div>
        <ul class="tags-list">
          <li>
            <a href="#tag1" data-filter="tag-1">Tag 1</a>
          </li>
          <li>
            <a href="#tag2" data-filter="tag-2">Tag 2</a>
          </li>
          <li>
            <a href="#tag3" class="selected" data-filter="tag-3">
              Tag 3
              <i class="remove-tag" data-remove-tag="tag-3">&times;</i>
            </a>
          </li>
          <li>
            <a href="#tag4" data-filter="tag-4">Tag 4</a>
          </li>
        </ul>
      </div>
      <h3>See more</h3>
      <div>
        <div class="see-more">
          <button class="btn" type="button" data-more="true">See more</button>
        </div>
      </div>
    </section>
    <section class="sg-section" id="cancel-confirm">
      <h2>05. Cancel or Confirm prompt</h2>
      <div class="prompt">
        <a class="prompt__cancel" href="#cancel">Cancel</a>
        <button class="btn btn--primary prompt__confirm" type="button">Update profile</button>
      </div>
    </section>
    <section class="sg-section" id="like">
      <h2>06. Like or Liked button</h2>
      <div class="card">
        <div class="card__footer">
          <div>
            <button class="card__btn card__like delta" data-like="see-the-northern-lights">
              <svg class="icon-heart" role="presentation">
                <use xlink:href="<%= asset_url("icons/icons-defs.svg" + "#heart") %>"></use>
              </svg>
              Like
            </button>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card__footer">
          <div>
            <button class="card__btn card__like delta" data-like="see-the-northern-lights">
              <svg class="icon-heart icon-heart--liked" role="presentation">
                <use xlink:href="<%= asset_url("icons/icons-defs.svg" + "#heart") %>"></use>
              </svg>
              Liked
            </button>
          </div>
        </div>
      </div>
    </section>
  </main>
</body>