config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  scope '/:locale' do
    root to: 'home#index'

    get 'home/index'

    get 'styles/atoms'

    get 'styles/molecules'

    get 'styles/organisms'

    resources :sessions, only: [:new, :create, :destroy]

    resources :users, only: [:new, :create, :edit, :update] do
      resources :goals
    end

    resources :ideas do
      resources :comments
      resources :photos
    end

    get 'account', to: 'account#edit'
    patch 'account', to: 'account#update'
    get 'account/ideas'
    get 'account/goals'

    get 'login', to: 'sessions#new'

    get 'signup', to: 'users#new'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :idea
  belongs_to :user
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 75 }

  belongs_to :user

  has_many :comments

  has_and_belongs_to_many :users

  scope :most_recent,          -> { order(created_at: :desc).limit(3) }
  scope :title_contains,       ->(term) { where('title LIKE ?', "%#{term}%") }
  scope :description_contains, ->(term) { where('description LIKE ?', "%#{term}%") }
  scope :search, ->(search_term) { title_contains(search_term).or(description_contains(search_term)) }

  paginates_per 9
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :ideas

  has_and_belongs_to_many :goals, class_name: 'Idea'

  has_secure_password

  validates :email, uniqueness: true
  validates :role, inclusion: { in: %w(registered admin) }

  after_initialize :default_role!
  before_validation :downcase_email

  mount_uploader :avatar, AvatarUploader

  private

  def downcase_email
    self.email = email.downcase if email #prevent from users with email:Nil in database
  end

  def default_role!
    self.role ||= 'registered'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def logged_in?
    session[:user_id].present?
  end

  def current_user
    if(@current_user.present?)
      return @current_user
    end

    @current_user = User.find(session[:user_id])
  end

  def ensure_authenticated
    redirect_to login_path unless(logged_in?)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :ensure_authenticated

  def create
    @idea = Idea.find(params[:idea_id])

    current_user.goals << @idea

    respond_to do |format|
      format.html { redirect_to idea_path(@idea) }
      format.js
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ideas = Idea.most_recent
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  include RolesHelper

  before_action :ensure_authenticated,   only: [:new, :create, :edit, :update] #this will stop any resources being loaded unnecessarily for anonymous users
  before_action :load_idea,              only: [:edit, :update, :destroy] #this will load Idea record before executing `ensure_owner` filter
  before_action :authorize_to_edit_idea, only: [:edit, :update, :destroy] #this make use of the Idea instance

  def index
    @search_term = params[:q]
    logger.info("Search completed using #{@search_term}.")
    @ideas = Idea.search(@search_term).page(params[:page])
  end

  def show
    @idea = Idea.find(params[:id])
    @comment = Comment.new
    @display_add_comment = session[:user_id].present?

    if(logged_in?) #check whether users are logged in or not
      @disable_add_goal = current_user.goals.exists?(@idea.id)
    end
  end

  def new
    @idea = Idea.new
  end

  def create
    user = User.find(session[:user_id])
    @idea = Idea.new(idea_resource_params)
    @idea.user = user
    if @idea.save
      redirect_to(ideas_path)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @idea.update(idea_resource_params)
      redirect_to(account_ideas_path)
    else
      render 'edit'
    end
  end

  def destroy
    @idea.destroy!
  end

  private

  def idea_resource_params
    params.require(:idea).permit(:title, :description, :photo_url, :done_count, :name_of_user)
  end

  def load_idea
    @idea = Idea.find(params[:id])
  end

  def authorize_to_edit_idea
    redirect_to(account_path) unless(can_edit?(@idea))
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  include RolesHelper

  before_action :ensure_authenticated
  before_action :load_idea
  before_action :authorize

  def index
    @query = params[:query]
    @query = @idea.title if @query.blank?

    @photos = Unsplash::Photo.random(query: @query, count: 3) # this returns an array of photos
  end

  def create
    @idea.update_attributes photo_url: params[:photo_url]

    redirect_to edit_idea_path(@idea)
  end

  private

  def load_idea
    @idea = Idea.find(params[:idea_id])
  end

  def authorize
    redirect_to account_path unless can_edit?(@idea)
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  def atoms
  end

  def molecules
  end

  def organisms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_admin, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if(@user.save)
      session[:user_id] = @user.id
      redirect_to ideas_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if(@user.update(edit_user_params))
      redirect_to account_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def edit_user_params
    params.require(:user).permit(:email, :name, :role)
  end

  def ensure_admin
     if(current_user.role == 'admin')
       return
     end

    redirect_to account_path
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
  # def has_goal?(goal)
  #   return false unless logged_in?
  # else
  #   return true
  # end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
  def can_edit?(goal)
    case(current_user.role)
    when 'admin' then true
    when 'registered' then current_user == goal.user
    else false
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_anonymous_user_header.html.erb
<nav class="site-header__nav">
  <ul class="main-navigation">
    <li><a href="#nolink"><%= translate('inspiration') %></a></li>
    <li><%= link_to(translate('signup'), signup_path) %></li>
    <li><%= link_to(translate('login'), login_path) %></li>
  </ul>
</nav>

app/views/application/_authenticated_user_header.html.erb
<nav class="site-header__nav">
  <ul class="main-navigation">
    <li><a href="#nolink"><%= translate('inspiration') %></a></li>
    <li><%= link_to(translate('account'), account_ideas_path) %></li>
    <li><%= link_to(translate('logout'), session_path(1), method: :delete) %></li>
  </ul>
</nav>

app/views/application/_footer.html.erb
<div class="content-wrapper">
  <!-- footer__logo -->
  <div class="logo logo--inverted footer__logo">
    <%= link_to('<span><i>My</i> Bucket List</span>'.html_safe, root_path) %>
  </div>
  <!-- footer__navigation -->
  <nav class="footer__navigation">
    <ul>
      <li><a href="#nolink">About</a></li>
      <li><%= link_to('Style guide', styles_atoms_path) %></li>
      <li><a href="#nolink">Terms of Use</a></li>
    </ul>
  </nav>
  <!-- Languages links -->
  <div>
    <h3  class="footer__logo">
      <%= link_to "🇬🇧", url_for(locale: :en) %>
      <%= link_to "🇫🇷", url_for(locale: :fr) %>
    </h3>
  </div>
  <!-- copyright -->
  <div>
    <p class="copyright">&copy; EPFL 2017-<%= Time.now.strftime("%Y") %></p>
  </div>
</div>

app/views/application/_header.html.erb
<div class="site-header">
  <div class="content-wrapper">
    <div class="logo">
      <%= link_to('<span><i>My</i> Bucket List</span>'.html_safe, root_path) %>
    </div>
    <%= render(partial: 'search_form') %>
    <% if(logged_in?) %>
      <%= render partial: 'authenticated_user_header' %>
    <% else %>
      <%= render partial: 'anonymous_user_header' %>
    <% end %>
  </div>
</div>

app/views/application/_idea_card.html.erb
<div class="card">
  <div class="card__thumb">
    <%= link_to(idea_path(idea)) do %>
      <%= render(partial: 'idea_photo', locals: { photo_url: photo_url }) %>
    <% end %>
    <div class="card__intro">
      <h4 class="card__title">
        <%= card_title %>
      </h4>
      <span><%= done_count %>
        have done this</span>
    </div>
  </div>
  <div class="card__footer">
    <button class="card__btn card__like delta" data-like="see-the-northern-lights">
      <svg class="icon-heart icon-heart--liked" role="presentation">
        <use xlink:href="<%= asset_url("icons/icons-defs.svg" + "#heart") %>"></use>
      </svg>
      Like
    </button>
    <% if(logged_in?) %>
      <%= form_tag(user_goals_path(current_user), remote: true, id: "goal-#{idea.id}") do %>
        <%= hidden_field_tag('idea_id', idea.id) %>
        <%= button_tag(class: 'btn delta', type: 'submit') do %>
          <svg class="icon-heart icon--sm" role="presentation">
            <use xlink:href="<%= asset_url("icons/icons-defs.svg" + "#pluss") %>"></use>
          </svg>
          Add Goal
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/application/_idea_photo.html.erb
<% if(photo_url.nil?) %>
  <%# use conditional to avoid error when the existing images have no values %>
    <img src="http://fpoimg.com/255x170" alt="Northern lights over mountain covered in snow">
  <% else %>
    <%= image_tag(photo_url) %>
  <% end %>

app/views/application/_search_form.html.erb
<%= form_tag(ideas_path, method: :get, class: 'global-search') do %>
  <div class="input-inline">
    <label class="input-group__label sr-only" for="q">Looking for inspiration?</label>
    <div class="input-row">
      <%= text_field_tag('q', nil, class: 'input-row__field', placeholder: 'e.g. Swimming with dolphins') %>
      <%= button_tag('Search', class: 'btn btn--inline btn--primary') %>
    </div>
  </div>
<% end %>